language: generic

cache:
  directories:
    - $HOME/.stack

install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version

script:
  - stack build
  - stack install
  - stack test

matrix:
  include:
   - os: linux
   - os: osx

before_deploy:
  - mv "$(which sjsp)" .
  - zip sjsp_"$(uname | awk '{ print tolower($0) }')".zip sjsp

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: HqCfkVdcgkqNiLaAliLOPhlaXwKE4wa0hzO41xZaNwrhacKwEuKhuQEeDWSigR3+ihgGieddVTDRM6RXz7FTv48oQv9On/cOgmZiMrGmhZsNTsQKsmy5gE/VZziPaI4ihcjCMFO2RzlNFiNDKKAhxXOysOg1bcc0ib8hwKsET+LZXoPBOfmaBWB3Ahu2f/YpTtBt6T+RPGyXMJ5Ryr1wGYtDVOetReWMO+PePnHr824+3soCUzMh83MQNvt9CH/pWpZryAPUXhK5QARhgDFrY4n1V09B9CgrAA+Oc85iHePoOjIyEaWPB9umzeNopJYv6KPzWy11wVThk3uRyuTazmynxtXG0jXoajeRRghcwzhXnBkP1xdNad0BVQFvzjPLvpvesmKqyutzfsA7k0nlp4T3EEVHuJ/wsPFe6wweZhRTqXIHhClOCd5L+3EkidQB4mL1pTG0ByL6/vzMqVusGf047unn26Prn3HLqcsJ5AzwX2C6Xeg+X81nd9NupTYDUfdy93Sqz2wvX8dSDqfES8FBcIh45jdR6o0/841uPcWtf/lNUg54TNvCiMEBsqS7t2Kv5iTAdQKzJdk8SpkGFpZSTdaGzQv3NpdmwqTzwaxBRFi2SdHthwh2IT7Ojg6ZegfcFKLE33eI2D/l+OZXlyH6MjmtMMSNnLtVDMkiPbk=
  file: ./*.zip
  file_glob: true
  on:
    repo: itchyny/sjsp
    tags: true
    all_branches: false
