name: CI

on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Build
      run: stack build
    - name: Install
      run: stack install
    - name: Test
      run: stack test
